# Generated by Django 6.0.1 on 2026-03-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
