# Generated by Django 6.0.1 on 2026-04-07 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0003_patient_is_profile_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='patients_pa_user_id_b78fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='vitals',
            index=models.Index(fields=['patient', 'recorded_at'], name='patients_vi_patient_120490_idx'),
        ),
    ]
