# Generated by Django 6.0.1 on 2026-04-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patients_pa_patient_927c52_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPConsent',
        ),
    ]
