# Generated by Django 6.0.1 on 2026-04-08 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_delete_otpconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='qr_code'),
        ),
        migrations.CreateModel(
            name='DoctorStaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accesses', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
