# Generated by Django 6.0.1 on 2026-04-12 04:35

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_qr_code_doctorstaffaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='known_allergies',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
