# Generated by Django 6.0.1 on 2026-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
