# Generated by Django 6.0.1 on 2026-03-29 18:02

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0003_patient_is_profile_complete'),
        ('records', '0002_medicalrecord_follow_up_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('SCAN_REPORT', 'Scan Report'), ('SCAN_IMAGE', 'Scan Image'), ('CONSENT_FORM', 'Consent Form'), ('OP_NOTES', 'Operation Notes'), ('DISCHARGE', 'Discharge Summary'), ('OTHER', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date']},
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='lab_tests_requested',
            new_name='scan_types',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='file',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='anesthesia_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='assessment',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='chief_complaint',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinical_indication',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='complications',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='contrast_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='disposition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='examination_findings',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fasting_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fasting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_instructions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gcs_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='history',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lab_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lab_results',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mode_of_arrival',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_progress',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='post_op_diagnosis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='post_op_instructions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pre_op_diagnosis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='priority',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='procedure_details',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='procedure_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='radiologist_report',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='severity',
            field=models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptom_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tests_ordered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_given',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='triage_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_type',
            field=models.CharField(choices=[('CONSULTATION', 'General Consultation'), ('PRESCRIPTION', 'Prescription Only'), ('LAB_TEST', 'Lab Test Request'), ('SCAN', 'Scan / Imaging'), ('PROCEDURE', 'Procedure / Surgery'), ('EMERGENCY', 'Emergency Visit'), ('FOLLOWUP', 'Follow-up Visit')], default='CONSULTATION', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_unit',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='Days', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('CREAM', 'Cream'), ('PATCH', 'Patch'), ('OTHER', 'Other')], default='TABLET', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('INH', 'Inhalation'), ('SL', 'Sublingual')], default='ORAL', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='special_instructions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QID', 'Four times daily'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('SOS', 'As needed (SOS)'), ('AC', 'Before food'), ('PC', 'After food'), ('HS', 'At bedtime')], default='OD', max_length=10),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'visit_date'], name='records_med_patient_d58c95_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_by', 'visit_date'], name='records_med_created_c47584_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['visit_type'], name='records_med_visit_t_faeb43_idx'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.medicalrecord'),
        ),
    ]
