# Generated by Django 6.0.1 on 2026-04-07 04:59

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicaldocument_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='results_interpretation',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('PROCEDURE', 'Planned Procedure'), ('EMERGENCY', 'Emergency Visit')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='suspected_diagnosis',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation & Prescription'), ('LAB_DIAGNOSTICS', 'Lab & Diagnostics'), ('PROCEDURE_EMERGENCY', 'Procedure & Emergency')], default='CONSULTATION', max_length=20),
        ),
    ]
