# Generated by Django 6.0.1 on 2026-04-07 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0004_patient_patients_pa_patient_927c52_idx_and_more'),
        ('records', '0004_medicalrecord_arrival_time_medicalrecord_is_followup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_by', 'status'], name='records_med_created_afa569_idx'),
        ),
    ]
