# Generated by Django 6.0.1 on 2026-04-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_medicalrecord_records_med_created_afa569_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorStaffAccess',
        ),
    ]
