# Generated by Django 6.0.1 on 2026-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('General', 'General'), ('Clinic', 'Clinic'), ('Multi-Specialty', 'Multi-Specialty'), ('Emergency', 'Emergency'), ('Research', 'Research'), ('Other', 'Other')], default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='verification_document',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the registration certificate', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
