# Generated by Django 6.0.1 on 2026-03-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff'), ('PATIENT', 'Patient')], db_index=True, max_length=20),
        ),
    ]
