from django.contrib.auth import get_user_model
from rest_framework import serializers

from hospitals.models import Hospital
from patients.models import Patient


User = get_user_model()


class RegisterSerializer(serializers.Serializer):
    """
    Serializer used for patient and doctor self-registration.
    Creates a User (and DoctorProfile if doctor).
    """

    username = serializers.CharField()
    password = serializers.CharField(write_only=True)
    email = serializers.EmailField()
    first_name = serializers.CharField()
    last_name = serializers.CharField(required=False, allow_blank=True)
    phone = serializers.CharField()
    role = serializers.ChoiceField(choices=[User.Roles.PATIENT, User.Roles.DOCTOR])
    hospital_id = serializers.IntegerField(required=False, allow_null=True)
    specialization = serializers.CharField(required=False, allow_blank=True)
    qualification = serializers.CharField(required=False, allow_blank=True)
    department = serializers.CharField(required=False, allow_blank=True)
    medical_reg_number = serializers.CharField(required=False, allow_blank=True)
    medical_council = serializers.CharField(required=False, allow_blank=True)
    years_of_experience = serializers.IntegerField(required=False)
    # patient profile fields (required when role=PATIENT)
    date_of_birth = serializers.DateField(required=False)
    gender = serializers.CharField(required=False)
    blood_group = serializers.CharField(required=False)
    address = serializers.CharField(required=False)
    known_allergies = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    emergency_contact_name = serializers.CharField(required=False)
    emergency_contact_phone = serializers.CharField(required=False)

    def validate(self, attrs):
        role = attrs.get("role")
        if role not in [User.Roles.PATIENT, User.Roles.DOCTOR]:
            raise serializers.ValidationError("Only patient and doctor registration is allowed.")
        if role == User.Roles.DOCTOR:
            required = ["specialization", "qualification", "department", "medical_reg_number", "medical_council"]
            missing = [f for f in required if not attrs.get(f)]
            if missing:
                raise serializers.ValidationError(f"Missing doctor fields: {', '.join(missing)}")
        if role == User.Roles.PATIENT:
            required = [
                "date_of_birth",
                "gender",
                "blood_group",
                "address",
                "emergency_contact_name",
                "emergency_contact_phone",
            ]
            missing = [f for f in required if not attrs.get(f)]
            if missing:
                raise serializers.ValidationError(f"Missing patient fields: {', '.join(missing)}")
        return attrs

    def create(self, validated_data):
        hospital_id = validated_data.pop("hospital_id", None)
        role = validated_data.pop("role")

        doctor_fields = [
            "specialization",
            "qualification",
            "department",
            "medical_reg_number",
            "medical_council",
            "years_of_experience",
        ]
        doctor_data = {k: validated_data.get(k) for k in list(validated_data.keys()) if k in doctor_fields}

        password = validated_data.pop("password")
        hospital = None
        if hospital_id:
            hospital = Hospital.objects.get(id=hospital_id)
        elif role != User.Roles.PATIENT:
            pass  # doctors need hospital; already validated above

        # For patients registering without a hospital, pick the first available one
        if role == User.Roles.PATIENT and hospital is None:
            hospital = Hospital.objects.first()

        patient_fields = [
            "date_of_birth",
            "gender",
            "blood_group",
            "address",
            "known_allergies",
            "emergency_contact_name",
            "emergency_contact_phone",
        ]
        patient_data = {k: validated_data.pop(k) for k in list(validated_data.keys()) if k in patient_fields}

        user = User.objects.create(
            role=role,
            hospital=hospital,
            is_active=True,
            **validated_data,
        )
        user.set_password(password)
        if role == User.Roles.DOCTOR:
            user.is_verified = False
        if role == User.Roles.PATIENT:
            user.is_verified = True
        user.save()
        if role == User.Roles.DOCTOR:
            pass  # Fields are automatically created on User now
        if role == User.Roles.PATIENT:
            gender_map = {"Male": "M", "Female": "F", "Other": "O", "M": "M", "F": "F", "O": "O"}
            g = patient_data.get("gender")
            patient_data["gender"] = gender_map.get(g, g)

            # patient_id is auto-generated by Patient.save() override
            # Ensure known_allergies is never None (EncryptedTextField doesn't allow null)
            patient_data["known_allergies"] = patient_data.get("known_allergies") or ""

            patient = Patient.objects.create(
                user=user,
                hospital=hospital,
                is_profile_complete=True,
                **patient_data,
            )

            # Generate QR code for the new patient
            try:
                import qrcode as qrcode_lib
                import io
                from django.conf import settings

                qr = qrcode_lib.QRCode(version=1, box_size=10, border=4)
                app_url = getattr(settings, "FRONTEND_URL", "http://localhost:3000")
                qr.add_data(f"{app_url}/qr/{patient.patient_id}")
                qr.make(fit=True)
                img = qr.make_image(fill_color="black", back_color="white")

                buffer = io.BytesIO()
                img.save(buffer, format="PNG")
                buffer.seek(0)

                if getattr(settings, "CLOUDINARY_CLOUD_NAME", ""):
                    import cloudinary.uploader
                    result = cloudinary.uploader.upload(
                        buffer,
                        public_id=f"meditrack/qr_codes/{patient.patient_id}",
                        resource_type="image",
                        overwrite=True,
                    )
                    patient.qr_code = result.get("public_id")
                else:
                    from django.core.files.base import ContentFile
                    patient.qr_code.save(
                        f"{patient.patient_id}.png",
                        ContentFile(buffer.getvalue()),
                        save=False,
                    )
                patient.save(update_fields=["qr_code"])
            except Exception as e:
                import logging
                logging.getLogger(__name__).warning(
                    f"QR code generation failed for {patient.patient_id}: {e}"
                )

        return user



class UserSerializer(serializers.ModelSerializer):
    """Serializer for listing and updating users."""

    department = serializers.SerializerMethodField()
    hospital_name = serializers.SerializerMethodField()
    created_at = serializers.SerializerMethodField()
    patient_id = serializers.SerializerMethodField()



    class Meta:
        model = User
        fields = (
            "id",
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "role",
            "hospital",
            "hospital_id",
            "hospital_name",
            "is_verified",
            "is_active",
            "department",

            "created_at",
            "specialization",
            "medical_reg_number",
            "patient_id",
            "status",
            "requires_password_change",
        )


        read_only_fields = ("id", "role", "is_verified", "status")

    def get_department(self, obj):
        return getattr(obj, "department", None)

    def get_hospital_name(self, obj):
        return obj.hospital.name if obj.hospital else "System"

    def get_created_at(self, obj):
        return obj.date_joined.isoformat() if obj.date_joined else None

    def get_patient_id(self, obj):
        if obj.role == "PATIENT":
            try:
                return obj.patient_profile.patient_id
            except:
                return None
        return None



from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.exceptions import AuthenticationFailed
from django.contrib.auth import authenticate

class LoginSerializer(TokenObtainPairSerializer):
    def validate(self, attrs):
        # Support login by either email or username
        login_input = attrs.get(self.username_field, "").strip()
        password = attrs.get("password", "")

        user = None

        # Try email lookup first
        if "@" in login_input:
            try:
                matched = User.objects.get(email__iexact=login_input)
                # Verify password manually
                if matched.check_password(password):
                    if not matched.is_active:
                        raise AuthenticationFailed("Your account has been deactivated. Please contact support.")
                    user = matched
                    self.user = matched  # keep self.user in sync
            except User.DoesNotExist:
                pass

        # Fall back to username lookup via default simplejwt flow
        if user is None:
            try:
                data = super().validate(attrs)
            except Exception as e:
                # Check if it failed because the user is inactive
                try:
                    user_obj = User.objects.get(**{self.username_field: attrs.get(self.username_field)})
                    if not user_obj.is_active:
                        raise AuthenticationFailed("Your account has been deactivated. Please contact support.")
                except User.DoesNotExist:
                    pass
                raise AuthenticationFailed("No active account found with the given credentials.")

            user = self.user  # set from super().validate() above
            if not user.is_active:
                raise AuthenticationFailed("Your account has been deactivated. Please contact support.")

        # Unified token generation
        role = user.role or ("ADMIN" if user.is_superuser else "USER")

        # Block unapproved doctors from logging in
        if role == "DOCTOR" and not user.is_verified:
            raise AuthenticationFailed(
                "Your account is pending admin approval. You will be notified once your account is approved."
            )
        
        # Intercept for 2FA on Admin/Hospital Admin
        if role in ["ADMIN", "HOSPITAL_ADMIN"]:
            import uuid
            from django.core.cache import cache
            temp_token = str(uuid.uuid4())
            # Store user.id in cache for 5 minutes
            cache.set(f"2fa_pending_{temp_token}", user.id, timeout=300)
            return {
                "requires_2fa": True,
                "temp_token": temp_token,
                "is_setup": bool(user.totp_secret),
                "role": role
            }

        from rest_framework_simplejwt.tokens import RefreshToken
        refresh = RefreshToken.for_user(user)
        return {
            "refresh": str(refresh),
            "access": str(refresh.access_token),
            "id": user.id,
            "email": user.email,
            "role": role,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "hospital_id": getattr(user, "hospital_id", None),
            "requires_password_change": getattr(user, "requires_password_change", False),
        }

from .models import AuditLog, Notification

class AuditLogSerializer(serializers.ModelSerializer):
    user = serializers.SerializerMethodField()

    class Meta:
        model = AuditLog
        fields = [
            "id", "timestamp", "user", "action", "target_model",
            "target_id", "description", "ip_address"
        ]

    def get_user(self, obj):
        return obj.user.email if obj.user else "System"


class NotificationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Notification
        fields = ["id", "message", "notification_type", "is_read", "created_at"]
